"""PostgreSQL models and transactional repositories for ChaosAgent."""

from .lifecycle import (
    ACTIVE_STATUSES,
    RUN_STATUSES,
    TERMINAL_STATUSES,
    IllegalRunTransitionError,
    RunStatus,
    legal_targets,
)
from .models import Base
from .repository import (
    AgentConfigurationRevisionRecord,
    ClaimedRun,
    DuplicateEventIDError,
    EventIdentityAndSequenceConflictError,
    EventSequenceConflictError,
    FinalReportConflictError,
    LeaseExpiredError,
    LeaseIdentity,
    LeaseNotExpiredError,
    LifecycleConflictError,
    LifecycleEvidence,
    PersistenceConflictError,
    PersistenceError,
    PersistenceIntegrityError,
    PersistenceProfileError,
    PersistenceRepository,
    ReferenceNotFoundError,
    RevisionConflictError,
    RevisionReference,
    RunEventRecord,
    RunRecord,
    RunReportRecord,
    ScenarioRevisionRecord,
    StaleLeaseError,
    create_postgres_engine,
)

__all__ = [
    "AgentConfigurationRevisionRecord",
    "ACTIVE_STATUSES",
    "Base",
    "ClaimedRun",
    "DuplicateEventIDError",
    "EventIdentityAndSequenceConflictError",
    "EventSequenceConflictError",
    "FinalReportConflictError",
    "IllegalRunTransitionError",
    "LeaseExpiredError",
    "LeaseIdentity",
    "LeaseNotExpiredError",
    "LifecycleConflictError",
    "LifecycleEvidence",
    "PersistenceConflictError",
    "PersistenceError",
    "PersistenceIntegrityError",
    "PersistenceProfileError",
    "PersistenceRepository",
    "ReferenceNotFoundError",
    "RUN_STATUSES",
    "RevisionConflictError",
    "RevisionReference",
    "RunStatus",
    "RunEventRecord",
    "RunRecord",
    "RunReportRecord",
    "ScenarioRevisionRecord",
    "StaleLeaseError",
    "TERMINAL_STATUSES",
    "create_postgres_engine",
    "legal_targets",
]
